import React, { Fragment } from 'react';
import Head from 'next/head';
import Hero from '../sections/landingPage/hero';
import Benefits from '../sections/landingPage/benefits';
import Navbar from '../sections/landingPage/navbar';
import Testimonials from '../sections/landingPage/testimonials';

const LandingPage: React.FunctionComponent = () => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sticky top-0 overflow-hidden">
        <Navbar navItems={['About', 'Benefits', 'Testimonies']}></Navbar>
      </div>
      <div className="h-screen w-auto pl-40 pr-10">
        <Hero></Hero>
      </div>
      <div className="h-screen w-auto pl-40 pr-20">
        <Benefits></Benefits>
      </div>
      <div className="h-screen w-auto pl-20 pr-20">
        <Testimonials></Testimonials>
      </div>
    </Fragment>
  );
};

export default LandingPage;
