# Generated by Django 4.1.7 on 2023-04-04 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='app_sph_lms.company'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='app_sph_lms.company'),
        ),
    ]
