# Generated by Django 4.1.7 on 2023-05-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app_sph_lms.course'),
        ),
        migrations.CreateModel(
            name='CourseTrainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_detail', to='app_sph_lms.course')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_detail', to='app_sph_lms.trainee')),
            ],
            options={
                'verbose_name': 'CourseTrainee',
                'verbose_name_plural': 'CourseTrainees',
                'db_table': 'app_sph_lms_course_trainees',
            },
        ),
    ]
