# Generated by Django 4.1.7 on 2023-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sph_lms', '0002_remove_course_status_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.URLField(max_length=600),
        ),
    ]
